# Generated by Django 5.2 on 2026-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('created_by', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=225)),
                ('modified_at', models.DateTimeField()),
            ],
        ),
    ]
