# Generated by Django 5.2 on 2026-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogs_modified_at_alter_blogs_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('produk', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Elektronik', 'Elektronik'), ('Aksesoris', 'Aksesoris'), ('Furniture', 'Furniture')], max_length=50)),
                ('jumlah', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal'],
                'indexes': [models.Index(fields=['-tanggal'], name='blog_app_tr_tanggal_de4838_idx'), models.Index(fields=['kategori'], name='blog_app_tr_kategor_c61c14_idx')],
            },
        ),
    ]
